# Generated by Django 6.0.3 on 2026-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_chatsession_chatmessage_delete_resumeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
